# Sprat
# Copyright (c) 2016 Peter McKay
# Free to use under the MIT license

version: '2'

services:

  analytics:
    build: ../analytics
    ports: 
      - "8008:8008"
    
  cms: 
    build: ../cms
    ports: 
      - "1337:1337"

  ui_web:
    build: ../ui_web
    ports: 
      - "8080:8080"
    links: 
      - cms
      - analytics
